{
 "title": "Cannabica Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Bot Usage Metricas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Actividad del Bot por Evento (Frecuencia)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (context_event) (count_over_time({container=~\"(.*php.*|.*nginx.*)\"} | json | context_event != \"\" [1h]))"
    }
   ]
  },
  {
   "title": "Distribución de Interacciones",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({container=~\"(.*php.*|.*nginx.*)\"} | json | context_event != \"\" [$__range])) by (context_event)",
     "legendFormat": "{{context_event}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Telegram details",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{container=~\"(.*php.*|.*nginx.*)\"} |= `telegram` or `webhook`"
    }
   ]
  },
  {
   "title": "Llamados a la API",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{container=~\"(.*php.*|.*nginx.*)\"} |= `/api`"
    }
   ]
  },
  {
   "title": "General overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "NGINX",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "{container=\"openindoor-nginx-1\"} |= ``"
      }
     ]
    },
    {
     "title": "PHP Container",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "{service_name=\"openindoor-php-1\"} |= ``"
      }
     ]
    },
    {
     "title": "DB",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "{service_name=\"openindoor-db-1\"} |= ``"
      },
      {}
     ]
    }
   ]
  }
 ]
}